before:
  hooks:
    - go mod tidy
    - go test

builds:
- id: semver-sort
  goos:
    - darwin
    - linux
  goarch:
    - amd64
    - arm64

archives:
- builds:
  - semver-sort

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
